/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_AHB1ENR (*(volatile uint32_t *)0x40023830)
#define GPIOA_MODER (*(volatile uint32_t *)0x40020000)
#define GPIOA_ODR (*(volatile uint32_t *)0x400200014)
#define GPIOA_IDR (*(volatile uint32_t *)0x400200010)

void simple_delay(volatile uint32_t time_delay) {
    while (time_delay > 0) {
        time_delay--; // The processor counts backwards and "wastes time"
    }
}

int main(void)
{
    // 1. Enable Clock for GPIOA
    RCC_AHB1ENR |= (1 << 0);

    // 2. Configure GPIOA Pins
    // Clear mode bits for PA0-PA3 (LEDs) and PA5 (Button)
    // Bits 0-7 are for PA0-PA3. Bits 10-11 are for PA5.
    GPIOA_MODER &= ~((0xFF << 0) | (0x3 << 10));

    // Set PA0-PA3 as General Purpose Output (01). Binary 0101 0101 = 0x55
    // PA5 remains 00 (Input Mode)
    GPIOA_MODER |= (0x55 << 0);

    int mode = 0; // State machine variable

    while(1) {

        // --- BUTTON POLLING & DEBOUNCING ---
        // Check if Button on PA5 is HIGH (Pressed)
        if (GPIOA_IDR & (1 << 5)) {

            simple_delay(20000); // 1st Debounce delay (ignore noise)

            // Confirm the button is still pressed
            if (GPIOA_IDR & (1 << 5)) {
                mode++; // Change state

                // Wrap around state (0, 1, 2)
                if(mode > 2) {
                    mode = 0;
                }

                // Wait until the button is released (Blocking)
                while(GPIOA_IDR & (1 << 5)) {
                    // Do nothing, just wait
                }

                simple_delay(20000); // 2nd Debounce delay for release
            }
        }

        // --- STATE MACHINE ---
        switch(mode) {

            case 0: // STATE 0: All LEDs OFF
                GPIOA_ODR &= ~(0xF << 0);
                // Note: Blocking delays removed here to keep button responsive
                break;

            case 1: // STATE 1: All LEDs ON
                GPIOA_ODR |= (0xF << 0);
                // Note: Blocking delays removed here to keep button responsive
                break;

            case 2: // STATE 2: LED Chaser Animation
                // Iterate through pins PA0 to PA3
                for(int i = 0; i < 4; i++) {

                    // Turn ON the current LED by setting the i-th bit to 1
                    GPIOA_ODR |= (1 << i);

                    // Wait to make the LED state visible to the human eye
                    simple_delay(500000);

                    // Turn OFF the current LED by clearing the i-th bit to 0
                    GPIOA_ODR &= ~(1 << i);
                }
                break;
        }
    }
}
