/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* =========================================================================
 * 1. MEMORY MAPPING (Memory-Mapped I/O)
 * Instead of using libraries, we manually define the physical addresses
 * of the registers (Found on page 50 of the F401RE Reference Manual).
 * ========================================================================= */

// RCC Register (Reset and Clock Control): Manages power/clocking of the chip
#define RCC_AHB1ENR (*(volatile uint32_t *)0x40023830)

// GPIOA Registers (General Purpose Input/Output - Port A)
#define GPIOA_MODER (*(volatile uint32_t *)0x40020000) // Sets the mode (Input/Output)
#define GPIOA_ODR   (*(volatile uint32_t *)0x40020014) // Physically turns the pin on or off

/* =========================================================================
 * 2. "CRUDE" DELAY FUNCTION
 * Since we don't have an RTOS or hardware timers configured yet, we use
 * a simple loop to waste processor time.
 * ========================================================================= */
void simple_delay(volatile uint32_t time_delay) {
    while (time_delay > 0) {
        time_delay--; // The processor counts backwards and "wastes time"
    }
}

/* =========================================================================
 * 3. MAIN PROGRAM
 * ========================================================================= */
int main(void) {

    // STEP 1: Turn on the main switch (clock) for Port A
    // Bit 0 of the RCC_AHB1ENR register enables the GPIOA clock.
    RCC_AHB1ENR |= (1 << 0); // Set the bit at position 0 to '1'

    // STEP 2: Configure Pin PA5 as Output
    // In the MODER register, each pin uses 2 bits. PA5 uses bits 10 and 11.
    // To configure it as an Output, we must write '01' into those two bits.
    GPIOA_MODER &= ~(3 << 10); // First, "clear" bits 10 and 11 by setting them to '00'
    GPIOA_MODER |=  (1 << 10); // Then set only bit 10 to '1' (result: '01')

    // STEP 3: The Infinite Life Cycle (Superloop)
    while (1) {

        // Turn on the LED (Set bit 5 of the ODR register to '1')
        GPIOA_ODR |= (1 << 5);

        // Wait a bit
        simple_delay(500000);

        // Turn off the LED (Set bit 5 of the ODR register to '0' using bitwise AND NOT)
        GPIOA_ODR &= ~(1 << 5);

        // Wait a bit
        simple_delay(500000);
    }
}
