/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//RCC Register (Reset and Clock Control): Manages power/clocking of the chip
#define RCC_AHB1ENR (*(volatile uint32_t *)0x40023830)

//Memory Mapping
#define GPIOB_MODER (*(volatile uint32_t *)0x40020400) //MODER porta B
#define GPIOB_IDR (*(volatile uint32_t *)0x40020410) //IDR porta B
#define GPIOA_MODER (*(volatile uint32_t *)0x40020000) //MODER porta A
#define GPIOA_ODR (*(volatile uint32_t *)0x40020014) //ODR porta A

void simple_delay(volatile uint32_t time_delay) {
    while (time_delay > 0) {
        time_delay--; // The processor counts backwards and "wastes time"
    }
}

int main(void){

	RCC_AHB1ENR |= (3 << 0); //accendo il clock nei primi due bit, che corrispondono a porta A e B

	GPIOB_MODER &= ~(3 << 6); //indicato come IDR i bit del pin 3 porta B

	GPIOA_MODER &= ~(3 << 14); //pulisco i bit del pin 7 della porta A
	GPIOA_MODER |= (1 << 14); //indico come ODR



	while(1){
		if (GPIOB_IDR &= (1 << 3)){
			GPIOA_ODR |= (1 << 7);
		}else { GPIOA_ODR &=  ~(1 << 7);
	}

}
}
